# Generated by Django 2.2.7 on 2019-11-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qus',
            field=models.CharField(max_length=254, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sendnotification',
            name='message',
            field=models.CharField(max_length=254),
        ),
    ]
